language: python
python:
  - "2.6"
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - pip install "pip==1.3.1"  # fix issue with fanstatic==1.0a
  - pip install -e . -r https://raw.github.com/Kotti/Kotti/0.9.2/requirements.txt
  - pip install "Kotti==0.9.2"
  - pip install "wsgi_intercept==0.5.1"
  - python setup.py dev
script: py.test --tb=native --cov=kotti_contactform --cov-report=term-missing
