language: python
python:
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_contactform
  - KOTTI_TEST_DB_STRING=mysql+oursql://root@localhost:3306/kotti_contactform
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - pip install -U pip
  - pip install psycopg2 oursql
  - pip install -e . -r https://raw.github.com/Kotti/Kotti/testing/requirements.txt
  - pip install "wsgi_intercept==0.5.1"
  - python setup.py dev
before_script:
  - psql -c 'create database kotti_contactform;' -U postgres
  - mysql -e 'create database kotti_contactform;'
script: py.test --tb=native --cov=kotti_contactform --cov-report=term-missing
notifications:
  irc: "irc.freenode.org#kotti"
  email: false
